name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and run containers with resource limits
        run: docker compose up --build --exit-code-from flask-app

      - name: Wait for MySQL to be ready
        run: ./wait-for-it.sh mysql-db:3306 --timeout=60 --strict -- echo "MySQL is ready"

      - name: Run vulnerability scan
        run: sh security/test-vulns.sh

      - name: Push image to Docker Hub
        run: |
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
