name: CI
on:
  push:
    branches: [ main ] #"#""""
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and run containers with resource limits
        run: docker compose up --build --abort-on-container-exit
      - name: Run vulnerability scan
        run: sh security/test-vulns.sh
      - name: Push image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest